export const outcomes = [

    {variable: "use_outcome_alcohol___1", drug: "alcohol", outcome: "use", definition: "Any use within a timeframe" },
    {variable: "use_outcome_alcohol___2", drug: "alcohol", outcome: "use", definition: "Frequency of use within a timeframe" },
    {variable: "use_outcome_alcohol___3", drug: "alcohol", outcome: "use", definition: "Volume of use within a timeframe" },
    {variable: "use_outcome_alcohol___4", drug: "alcohol", outcome: "use", definition: "Proportion currently using" },
    {variable: "use_outcome_alcohol___5", drug: "alcohol", outcome: "use", definition: "Any use within lifetime" },
    {variable: "use_outcome_alcohol___6", drug: "alcohol", outcome: "use", definition: "Any risky use within a timeframe" },
    {variable: "use_outcome_alcohol___7", drug: "alcohol", outcome: "use", definition: "Frequency of risky use within a timeframe" },
    {variable: "use_outcome_alcohol___8", drug: "alcohol", outcome: "use", definition: "Any risky use within lifetime" },
    {variable: "use_outcome_alcohol___9", drug: "alcohol", outcome: "use", definition: "Proportion achieving abstinence" },
    {variable: "use_outcome_alcohol___10", drug: "alcohol", outcome: "use", definition: "Proportion achieving abstinence" },
    {variable: "use_outcome_alcohol___11", drug: "alcohol", outcome: "use", definition: "Proportion who attempted to quit use" },
    {variable: "use_outcome_alcohol___12", drug: "alcohol", outcome: "use", definition: "Bio validation of use" },
    {variable: "use_outcome_alcohol___13", drug: "alcohol", outcome: "use", definition: "Sales data (proxy)" },
    {variable: "use_outcome_alcohol___14", drug: "alcohol", outcome: "use", definition: "Proportion living in a use free home" },

    {variable: "use_outcome_coffee___1", drug: "coffee", outcome: "use", definition: "Any use within a timeframe" },
    {variable: "use_outcome_coffee___2", drug: "coffee", outcome: "use", definition: "Frequency of use within a timeframe" },
    {variable: "use_outcome_coffee___3", drug: "coffee", outcome: "use", definition: "Volume of use within a timeframe" },
    {variable: "use_outcome_coffee___4", drug: "coffee", outcome: "use", definition: "Proportion currently using" },
    {variable: "use_outcome_coffee___5", drug: "coffee", outcome: "use", definition: "Any use within lifetime" },
    {variable: "use_outcome_coffee___6", drug: "coffee", outcome: "use", definition: "Any risky use within a timeframe" },
    {variable: "use_outcome_coffee___7", drug: "coffee", outcome: "use", definition: "Frequency of risky use within a timeframe" },
    {variable: "use_outcome_coffee___8", drug: "coffee", outcome: "use", definition: "Any risky use within lifetime" },
    {variable: "use_outcome_coffee___9", drug: "coffee", outcome: "use", definition: "Proportion achieving abstinence" },
    {variable: "use_outcome_coffee___10", drug: "coffee", outcome: "use", definition: "Proportion achieving abstinence" },
    {variable: "use_outcome_coffee___11", drug: "coffee", outcome: "use", definition: "Proportion who attempted to quit use" },
    {variable: "use_outcome_coffee___12", drug: "coffee", outcome: "use", definition: "Bio validation of use" },
    {variable: "use_outcome_coffee___13", drug: "coffee", outcome: "use", definition: "Sales data (proxy)" },
    {variable: "use_outcome_coffee___14", drug: "coffee", outcome: "use", definition: "Proportion living in a use free home" },

    {variable: "use_outcome_pharma___1", drug: "pharmaceuticals", outcome: "use", definition: "Any use within a timeframe" },
    {variable: "use_outcome_pharma___2", drug: "pharmaceuticals", outcome: "use", definition: "Frequency of use within a timeframe" },
    {variable: "use_outcome_pharma___3", drug: "pharmaceuticals", outcome: "use", definition: "Volume of use within a timeframe" },
    {variable: "use_outcome_pharma___4", drug: "pharmaceuticals", outcome: "use", definition: "Proportion currently using" },
    {variable: "use_outcome_pharma___5", drug: "pharmaceuticals", outcome: "use", definition: "Any use within lifetime" },
    {variable: "use_outcome_pharma___6", drug: "pharmaceuticals", outcome: "use", definition: "Any risky use within a timeframe" },
    {variable: "use_outcome_pharma___7", drug: "pharmaceuticals", outcome: "use", definition: "Frequency of risky use within a timeframe" },
    {variable: "use_outcome_pharma___8", drug: "pharmaceuticals", outcome: "use", definition: "Any risky use within lifetime" },
    {variable: "use_outcome_pharma___9", drug: "pharmaceuticals", outcome: "use", definition: "Proportion achieving abstinence" },
    {variable: "use_outcome_pharma___10", drug: "pharmaceuticals", outcome: "use", definition: "Proportion achieving abstinence" },
    {variable: "use_outcome_pharma___11", drug: "pharmaceuticals", outcome: "use", definition: "Proportion who attempted to quit use" },
    {variable: "use_outcome_pharma___12", drug: "pharmaceuticals", outcome: "use", definition: "Bio validation of use" },
    {variable: "use_outcome_pharma___13", drug: "pharmaceuticals", outcome: "use", definition: "Sales data (proxy)" },
    {variable: "use_outcome_pharma___14", drug: "pharmaceuticals", outcome: "use", definition: "Proportion living in a use free home" },

    {variable: "use_outcome_depress___1", drug: "depressant", outcome: "use", definition: "Any use within a timeframe" },
    {variable: "use_outcome_depress___2", drug: "depressant", outcome: "use", definition: "Frequency of use within a timeframe" },
    {variable: "use_outcome_depress___3", drug: "depressant", outcome: "use", definition: "Volume of use within a timeframe" },
    {variable: "use_outcome_depress___4", drug: "depressant", outcome: "use", definition: "Proportion currently using" },
    {variable: "use_outcome_depress___5", drug: "depressant", outcome: "use", definition: "Any use within lifetime" },
    {variable: "use_outcome_depress___6", drug: "depressant", outcome: "use", definition: "Any risky use within a timeframe" },
    {variable: "use_outcome_depress___7", drug: "depressant", outcome: "use", definition: "Frequency of risky use within a timeframe" },
    {variable: "use_outcome_depress___8", drug: "depressant", outcome: "use", definition: "Any risky use within lifetime" },
    {variable: "use_outcome_depress___9", drug: "depressant", outcome: "use", definition: "Proportion achieving abstinence" },
    {variable: "use_outcome_depress___10", drug: "depressant", outcome: "use", definition: "Proportion achieving abstinence" },
    {variable: "use_outcome_depress___11", drug: "depressant", outcome: "use", definition: "Proportion who attempted to quit use" },
    {variable: "use_outcome_depress___12", drug: "depressant", outcome: "use", definition: "Bio validation of use" },
    {variable: "use_outcome_depress___13", drug: "depressant", outcome: "use", definition: "Sales data (proxy)" },
    {variable: "use_outcome_depress___14", drug: "depressant", outcome: "use", definition: "Proportion living in a use free home" },

    {variable: "use_outcome_hall___1", drug: "hallucinogen", outcome: "use", definition: "Any use within a timeframe" },
    {variable: "use_outcome_hall___2", drug: "hallucinogen", outcome: "use", definition: "Frequency of use within a timeframe" },
    {variable: "use_outcome_hall___3", drug: "hallucinogen", outcome: "use", definition: "Volume of use within a timeframe" },
    {variable: "use_outcome_hall___4", drug: "hallucinogen", outcome: "use", definition: "Proportion currently using" },
    {variable: "use_outcome_hall___5", drug: "hallucinogen", outcome: "use", definition: "Any use within lifetime" },
    {variable: "use_outcome_hall___6", drug: "hallucinogen", outcome: "use", definition: "Any risky use within a timeframe" },
    {variable: "use_outcome_hall___7", drug: "hallucinogen", outcome: "use", definition: "Frequency of risky use within a timeframe" },
    {variable: "use_outcome_hall___8", drug: "hallucinogen", outcome: "use", definition: "Any risky use within lifetime" },
    {variable: "use_outcome_hall___9", drug: "hallucinogen", outcome: "use", definition: "Proportion achieving abstinence" },
    {variable: "use_outcome_hall___10", drug: "hallucinogen", outcome: "use", definition: "Proportion achieving abstinence" },
    {variable: "use_outcome_hall___11", drug: "hallucinogen", outcome: "use", definition: "Proportion who attempted to quit use" },
    {variable: "use_outcome_hall___12", drug: "hallucinogen", outcome: "use", definition: "Bio validation of use" },
    {variable: "use_outcome_hall___13", drug: "hallucinogen", outcome: "use", definition: "Sales data (proxy)" },
    {variable: "use_outcome_hall___14", drug: "hallucinogen", outcome: "use", definition: "Proportion living in a use free home" },

    {variable: "use_outcome_ped___1", drug: "performance enhancing drug", outcome: "use", definition: "Any use within a timeframe" },
    {variable: "use_outcome_ped___2", drug: "performance enhancing drug", outcome: "use", definition: "Frequency of use within a timeframe" },
    {variable: "use_outcome_ped___3", drug: "performance enhancing drug", outcome: "use", definition: "Volume of use within a timeframe" },
    {variable: "use_outcome_ped___4", drug: "performance enhancing drug", outcome: "use", definition: "Proportion currently using" },
    {variable: "use_outcome_ped___5", drug: "performance enhancing drug", outcome: "use", definition: "Any use within lifetime" },
    {variable: "use_outcome_ped___6", drug: "performance enhancing drug", outcome: "use", definition: "Any risky use within a timeframe" },
    {variable: "use_outcome_ped___7", drug: "performance enhancing drug", outcome: "use", definition: "Frequency of risky use within a timeframe" },
    {variable: "use_outcome_ped___8", drug: "performance enhancing drug", outcome: "use", definition: "Any risky use within lifetime" },
    {variable: "use_outcome_ped___9", drug: "performance enhancing drug", outcome: "use", definition: "Proportion achieving abstinence" },
    {variable: "use_outcome_ped___10", drug: "performance enhancing drug", outcome: "use", definition: "Proportion achieving abstinence" },
    {variable: "use_outcome_ped___11", drug: "performance enhancing drug", outcome: "use", definition: "Proportion who attempted to quit use" },
    {variable: "use_outcome_ped___12", drug: "performance enhancing drug", outcome: "use", definition: "Bio validation of use" },
    {variable: "use_outcome_ped___13", drug: "performance enhancing drug", outcome: "use", definition: "Sales data (proxy)" },
    {variable: "use_outcome_ped___14", drug: "performance enhancing drug", outcome: "use", definition: "Proportion living in a use free home" },

    {variable: "use_outcome_opioid___1", drug: "opioid", outcome: "use", definition: "Any use within a timeframe" },
    {variable: "use_outcome_opioid___2", drug: "opioid", outcome: "use", definition: "Frequency of use within a timeframe" },
    {variable: "use_outcome_opioid___3", drug: "opioid", outcome: "use", definition: "Volume of use within a timeframe" },
    {variable: "use_outcome_opioid___4", drug: "opioid", outcome: "use", definition: "Proportion currently using" },
    {variable: "use_outcome_opioid___5", drug: "opioid", outcome: "use", definition: "Any use within lifetime" },
    {variable: "use_outcome_opioid___6", drug: "opioid", outcome: "use", definition: "Any risky use within a timeframe" },
    {variable: "use_outcome_opioid___7", drug: "opioid", outcome: "use", definition: "Frequency of risky use within a timeframe" },
    {variable: "use_outcome_opioid___8", drug: "opioid", outcome: "use", definition: "Any risky use within lifetime" },
    {variable: "use_outcome_opioid___9", drug: "opioid", outcome: "use", definition: "Proportion achieving abstinence" },
    {variable: "use_outcome_opioid___10", drug: "opioid", outcome: "use", definition: "Proportion achieving abstinence" },
    {variable: "use_outcome_opioid___11", drug: "opioid", outcome: "use", definition: "Proportion who attempted to quit use" },
    {variable: "use_outcome_opioid___12", drug: "opioid", outcome: "use", definition: "Bio validation of use" },
    {variable: "use_outcome_opioid___13", drug: "opioid", outcome: "use", definition: "Sales data (proxy)" },
    {variable: "use_outcome_opioid___14", drug: "opioid", outcome: "use", definition: "Proportion living in a use free home" },

    {variable: "use_outcome_inhalants___1", drug: "inhalants", outcome: "use", definition: "Any use within a timeframe" },
    {variable: "use_outcome_inhalants___2", drug: "inhalants", outcome: "use", definition: "Frequency of use within a timeframe" },
    {variable: "use_outcome_inhalants___3", drug: "inhalants", outcome: "use", definition: "Volume of use within a timeframe" },
    {variable: "use_outcome_inhalants___4", drug: "inhalants", outcome: "use", definition: "Proportion currently using" },
    {variable: "use_outcome_inhalants___5", drug: "inhalants", outcome: "use", definition: "Any use within lifetime" },
    {variable: "use_outcome_inhalants___6", drug: "inhalants", outcome: "use", definition: "Any risky use within a timeframe" },
    {variable: "use_outcome_inhalants___7", drug: "inhalants", outcome: "use", definition: "Frequency of risky use within a timeframe" },
    {variable: "use_outcome_inhalants___8", drug: "inhalants", outcome: "use", definition: "Any risky use within lifetime" },
    {variable: "use_outcome_inhalants___9", drug: "inhalants", outcome: "use", definition: "Proportion achieving abstinence" },
    {variable: "use_outcome_inhalants___10", drug: "inhalants", outcome: "use", definition: "Proportion achieving abstinence" },
    {variable: "use_outcome_inhalants___11", drug: "inhalants", outcome: "use", definition: "Proportion who attempted to quit use" },
    {variable: "use_outcome_inhalants___12", drug: "inhalants", outcome: "use", definition: "Bio validation of use" },
    {variable: "use_outcome_inhalants___13", drug: "inhalants", outcome: "use", definition: "Sales data (proxy)" },
    {variable: "use_outcome_inhalants___14", drug: "inhalants", outcome: "use", definition: "Proportion living in a use free home" },

    {variable: "use_outcome_cocaine___1", drug: "cocaine", outcome: "use", definition: "Any use within a timeframe" },
    {variable: "use_outcome_cocaine___2", drug: "cocaine", outcome: "use", definition: "Frequency of use within a timeframe" },
    {variable: "use_outcome_cocaine___3", drug: "cocaine", outcome: "use", definition: "Volume of use within a timeframe" },
    {variable: "use_outcome_cocaine___4", drug: "cocaine", outcome: "use", definition: "Proportion currently using" },
    {variable: "use_outcome_cocaine___5", drug: "cocaine", outcome: "use", definition: "Any use within lifetime" },
    {variable: "use_outcome_cocaine___6", drug: "cocaine", outcome: "use", definition: "Any risky use within a timeframe" },
    {variable: "use_outcome_cocaine___7", drug: "cocaine", outcome: "use", definition: "Frequency of risky use within a timeframe" },
    {variable: "use_outcome_cocaine___8", drug: "cocaine", outcome: "use", definition: "Any risky use within lifetime" },
    {variable: "use_outcome_cocaine___9", drug: "cocaine", outcome: "use", definition: "Proportion achieving abstinence" },
    {variable: "use_outcome_cocaine___10", drug: "cocaine", outcome: "use", definition: "Proportion achieving abstinence" },
    {variable: "use_outcome_cocaine___11", drug: "cocaine", outcome: "use", definition: "Proportion who attempted to quit use" },
    {variable: "use_outcome_cocaine___12", drug: "cocaine", outcome: "use", definition: "Bio validation of use" },
    {variable: "use_outcome_cocaine___13", drug: "cocaine", outcome: "use", definition: "Sales data (proxy)" },
    {variable: "use_outcome_cocaine___14", drug: "cocaine", outcome: "use", definition: "Proportion living in a use free home" },

    {variable: "use_outcome_e___1", drug: "ecstasy", outcome: "use", definition: "Any use within a timeframe" },
    {variable: "use_outcome_e___2", drug: "ecstasy", outcome: "use", definition: "Frequency of use within a timeframe" },
    {variable: "use_outcome_e___3", drug: "ecstasy", outcome: "use", definition: "Volume of use within a timeframe" },
    {variable: "use_outcome_e___4", drug: "ecstasy", outcome: "use", definition: "Proportion currently using" },
    {variable: "use_outcome_e___5", drug: "ecstasy", outcome: "use", definition: "Any use within lifetime" },
    {variable: "use_outcome_e___6", drug: "ecstasy", outcome: "use", definition: "Any risky use within a timeframe" },
    {variable: "use_outcome_e___7", drug: "ecstasy", outcome: "use", definition: "Frequency of risky use within a timeframe" },
    {variable: "use_outcome_e___8", drug: "ecstasy", outcome: "use", definition: "Any risky use within lifetime" },
    {variable: "use_outcome_e___9", drug: "ecstasy", outcome: "use", definition: "Proportion achieving abstinence" },
    {variable: "use_outcome_e___10", drug: "ecstasy", outcome: "use", definition: "Proportion achieving abstinence" },
    {variable: "use_outcome_e___11", drug: "ecstasy", outcome: "use", definition: "Proportion who attempted to quit use" },
    {variable: "use_outcome_e___12", drug: "ecstasy", outcome: "use", definition: "Bio validation of use" },
    {variable: "use_outcome_e___13", drug: "ecstasy", outcome: "use", definition: "Sales data (proxy)" },
    {variable: "use_outcome_e___14", drug: "ecstasy", outcome: "use", definition: "Proportion living in a use free home" },

    {variable: "use_outcome_meth___1", drug: "methamphetamines", outcome: "use", definition: "Any use within a timeframe" },
    {variable: "use_outcome_meth___2", drug: "methamphetamines", outcome: "use", definition: "Frequency of use within a timeframe" },
    {variable: "use_outcome_meth___3", drug: "methamphetamines", outcome: "use", definition: "Volume of use within a timeframe" },
    {variable: "use_outcome_meth___4", drug: "methamphetamines", outcome: "use", definition: "Proportion currently using" },
    {variable: "use_outcome_meth___5", drug: "methamphetamines", outcome: "use", definition: "Any use within lifetime" },
    {variable: "use_outcome_meth___6", drug: "methamphetamines", outcome: "use", definition: "Any risky use within a timeframe" },
    {variable: "use_outcome_meth___7", drug: "methamphetamines", outcome: "use", definition: "Frequency of risky use within a timeframe" },
    {variable: "use_outcome_meth___8", drug: "methamphetamines", outcome: "use", definition: "Any risky use within lifetime" },
    {variable: "use_outcome_meth___9", drug: "methamphetamines", outcome: "use", definition: "Proportion achieving abstinence" },
    {variable: "use_outcome_meth___10", drug: "methamphetamines", outcome: "use", definition: "Proportion achieving abstinence" },
    {variable: "use_outcome_meth___11", drug: "methamphetamines", outcome: "use", definition: "Proportion who attempted to quit use" },
    {variable: "use_outcome_meth___12", drug: "methamphetamines", outcome: "use", definition: "Bio validation of use" },
    {variable: "use_outcome_meth___13", drug: "methamphetamines", outcome: "use", definition: "Sales data (proxy)" },
    {variable: "use_outcome_meth___14", drug: "methamphetamines", outcome: "use", definition: "Proportion living in a use free home" },

    {variable: "use_outcome_cannabis___1", drug: "cannabis", outcome: "use", definition: "Any use within a timeframe" },
    {variable: "use_outcome_cannabis___2", drug: "cannabis", outcome: "use", definition: "Frequency of use within a timeframe" },
    {variable: "use_outcome_cannabis___3", drug: "cannabis", outcome: "use", definition: "Volume of use within a timeframe" },
    {variable: "use_outcome_cannabis___4", drug: "cannabis", outcome: "use", definition: "Proportion currently using" },
    {variable: "use_outcome_cannabis___5", drug: "cannabis", outcome: "use", definition: "Any use within lifetime" },
    {variable: "use_outcome_cannabis___6", drug: "cannabis", outcome: "use", definition: "Any risky use within a timeframe" },
    {variable: "use_outcome_cannabis___7", drug: "cannabis", outcome: "use", definition: "Frequency of risky use within a timeframe" },
    {variable: "use_outcome_cannabis___8", drug: "cannabis", outcome: "use", definition: "Any risky use within lifetime" },
    {variable: "use_outcome_cannabis___9", drug: "cannabis", outcome: "use", definition: "Proportion achieving abstinence" },
    {variable: "use_outcome_cannabis___10", drug: "cannabis", outcome: "use", definition: "Proportion achieving abstinence" },
    {variable: "use_outcome_cannabis___11", drug: "cannabis", outcome: "use", definition: "Proportion who attempted to quit use" },
    {variable: "use_outcome_cannabis___12", drug: "cannabis", outcome: "use", definition: "Bio validation of use" },
    {variable: "use_outcome_cannabis___13", drug: "cannabis", outcome: "use", definition: "Sales data (proxy)" },
    {variable: "use_outcome_cannabis___14", drug: "cannabis", outcome: "use", definition: "Proportion living in a use free home" },

    {variable: "use_outcome_vapes___1", drug: "vapes", outcome: "use", definition: "Any use within a timeframe" },
    {variable: "use_outcome_vapes___2", drug: "vapes", outcome: "use", definition: "Frequency of use within a timeframe" },
    {variable: "use_outcome_vapes___3", drug: "vapes", outcome: "use", definition: "Volume of use within a timeframe" },
    {variable: "use_outcome_vapes___4", drug: "vapes", outcome: "use", definition: "Proportion currently using" },
    {variable: "use_outcome_vapes___5", drug: "vapes", outcome: "use", definition: "Any use within lifetime" },
    {variable: "use_outcome_vapes___6", drug: "vapes", outcome: "use", definition: "Any risky use within a timeframe" },
    {variable: "use_outcome_vapes___7", drug: "vapes", outcome: "use", definition: "Frequency of risky use within a timeframe" },
    {variable: "use_outcome_vapes___8", drug: "vapes", outcome: "use", definition: "Any risky use within lifetime" },
    {variable: "use_outcome_vapes___9", drug: "vapes", outcome: "use", definition: "Proportion achieving abstinence" },
    {variable: "use_outcome_vapes___10", drug: "vapes", outcome: "use", definition: "Proportion achieving abstinence" },
    {variable: "use_outcome_vapes___11", drug: "vapes", outcome: "use", definition: "Proportion who attempted to quit use" },
    {variable: "use_outcome_vapes___12", drug: "vapes", outcome: "use", definition: "Bio validation of use" },
    {variable: "use_outcome_vapes___13", drug: "vapes", outcome: "use", definition: "Sales data (proxy)" },
    {variable: "use_outcome_vapes___14", drug: "vapes", outcome: "use", definition: "Proportion living in a use free home" },

    {variable: "use_outcome_smokeless___1", drug: "smokeless", outcome: "use", definition: "Any use within a timeframe" },
    {variable: "use_outcome_smokeless___2", drug: "smokeless", outcome: "use", definition: "Frequency of use within a timeframe" },
    {variable: "use_outcome_smokeless___3", drug: "smokeless", outcome: "use", definition: "Volume of use within a timeframe" },
    {variable: "use_outcome_smokeless___4", drug: "smokeless", outcome: "use", definition: "Proportion currently using" },
    {variable: "use_outcome_smokeless___5", drug: "smokeless", outcome: "use", definition: "Any use within lifetime" },
    {variable: "use_outcome_smokeless___6", drug: "smokeless", outcome: "use", definition: "Any risky use within a timeframe" },
    {variable: "use_outcome_smokeless___7", drug: "smokeless", outcome: "use", definition: "Frequency of risky use within a timeframe" },
    {variable: "use_outcome_smokeless___8", drug: "smokeless", outcome: "use", definition: "Any risky use within lifetime" },
    {variable: "use_outcome_smokeless___9", drug: "smokeless", outcome: "use", definition: "Proportion achieving abstinence" },
    {variable: "use_outcome_smokeless___10", drug: "smokeless", outcome: "use", definition: "Proportion achieving abstinence" },
    {variable: "use_outcome_smokeless___11", drug: "smokeless", outcome: "use", definition: "Proportion who attempted to quit use" },
    {variable: "use_outcome_smokeless___12", drug: "smokeless", outcome: "use", definition: "Bio validation of use" },
    {variable: "use_outcome_smokeless___13", drug: "smokeless", outcome: "use", definition: "Sales data (proxy)" },
    {variable: "use_outcome_smokeless___14", drug: "smokeless", outcome: "use", definition: "Proportion living in a use free home" },

    {variable: "use_outcome_cigarette___1", drug: "cigarette", outcome: "use", definition: "Any use within a timeframe" },
    {variable: "use_outcome_cigarette___2", drug: "cigarette", outcome: "use", definition: "Frequency of use within a timeframe" },
    {variable: "use_outcome_cigarette___3", drug: "cigarette", outcome: "use", definition: "Volume of use within a timeframe" },
    {variable: "use_outcome_cigarette___4", drug: "cigarette", outcome: "use", definition: "Proportion currently using" },
    {variable: "use_outcome_cigarette___5", drug: "cigarette", outcome: "use", definition: "Any use within lifetime" },
    {variable: "use_outcome_cigarette___6", drug: "cigarette", outcome: "use", definition: "Any risky use within a timeframe" },
    {variable: "use_outcome_cigarette___7", drug: "cigarette", outcome: "use", definition: "Frequency of risky use within a timeframe" },
    {variable: "use_outcome_cigarette___8", drug: "cigarette", outcome: "use", definition: "Any risky use within lifetime" },
    {variable: "use_outcome_cigarette___9", drug: "cigarette", outcome: "use", definition: "Proportion achieving abstinence" },
    {variable: "use_outcome_cigarette___10", drug: "cigarette", outcome: "use", definition: "Proportion achieving abstinence" },
    {variable: "use_outcome_cigarette___11", drug: "cigarette", outcome: "use", definition: "Proportion who attempted to quit use" },
    {variable: "use_outcome_cigarette___12", drug: "cigarette", outcome: "use", definition: "Bio validation of use" },
    {variable: "use_outcome_cigarette___13", drug: "cigarette", outcome: "use", definition: "Sales data (proxy)" },
    {variable: "use_outcome_cigarette___14", drug: "cigarette", outcome: "use", definition: "Proportion living in a use free home" },

    {variable: "use_outcome_other___1", drug: "other", outcome: "use", definition: "Any use within a timeframe" },
    {variable: "use_outcome_other___2", drug: "other", outcome: "use", definition: "Frequency of use within a timeframe" },
    {variable: "use_outcome_other___3", drug: "other", outcome: "use", definition: "Volume of use within a timeframe" },
    {variable: "use_outcome_other___4", drug: "other", outcome: "use", definition: "Proportion currently using" },
    {variable: "use_outcome_other___5", drug: "other", outcome: "use", definition: "Any use within lifetime" },
    {variable: "use_outcome_other___6", drug: "other", outcome: "use", definition: "Any risky use within a timeframe" },
    {variable: "use_outcome_other___7", drug: "other", outcome: "use", definition: "Frequency of risky use within a timeframe" },
    {variable: "use_outcome_other___8", drug: "other", outcome: "use", definition: "Any risky use within lifetime" },
    {variable: "use_outcome_other___9", drug: "other", outcome: "use", definition: "Proportion achieving abstinence" },
    {variable: "use_outcome_other___10", drug: "other", outcome: "use", definition: "Proportion achieving abstinence" },
    {variable: "use_outcome_other___11", drug: "other", outcome: "use", definition: "Proportion who attempted to quit use" },
    {variable: "use_outcome_other___12", drug: "other", outcome: "use", definition: "Bio validation of use" },
    {variable: "use_outcome_other___13", drug: "other", outcome: "use", definition: "Sales data (proxy)" },
    {variable: "use_outcome_other___14", drug: "other", outcome: "use", definition: "Proportion living in a use free home" },

    {variable: "use_outcome_second___1", drug: "second", outcome: "use", definition: "Any use within a timeframe" },
    {variable: "use_outcome_second___2", drug: "second", outcome: "use", definition: "Frequency of use within a timeframe" },
    {variable: "use_outcome_second___3", drug: "second", outcome: "use", definition: "Volume of use within a timeframe" },
    {variable: "use_outcome_second___4", drug: "second", outcome: "use", definition: "Proportion currently using" },
    {variable: "use_outcome_second___5", drug: "second", outcome: "use", definition: "Any use within lifetime" },
    {variable: "use_outcome_second___6", drug: "second", outcome: "use", definition: "Any risky use within a timeframe" },
    {variable: "use_outcome_second___7", drug: "second", outcome: "use", definition: "Frequency of risky use within a timeframe" },
    {variable: "use_outcome_second___8", drug: "second", outcome: "use", definition: "Any risky use within lifetime" },
    {variable: "use_outcome_second___9", drug: "second", outcome: "use", definition: "Proportion achieving abstinence" },
    {variable: "use_outcome_second___10", drug: "second", outcome: "use", definition: "Proportion achieving abstinence" },
    {variable: "use_outcome_second___11", drug: "second", outcome: "use", definition: "Proportion who attempted to quit use" },
    {variable: "use_outcome_second___12", drug: "second", outcome: "use", definition: "Bio validation of use" },
    {variable: "use_outcome_second___13", drug: "second", outcome: "use", definition: "Sales data (proxy)" },
    {variable: "use_outcome_second___14", drug: "second", outcome: "use", definition: "Proportion living in a use free home" },

    {variable: "harm_outcome_other___1", drug: "other", outcome: "harm", definition: "Proportion with substance-related injury within a timeframe" },
    {variable: "harm_outcome_other___2", drug: "other", outcome: "harm", definition: "Frequency of substance-related injury within a timeframe" },
    {variable: "harm_outcome_other___3", drug: "other", outcome: "harm", definition: "Related health conditions" },
    {variable: "harm_outcome_other___4", drug: "other", outcome: "harm", definition: "Related deaths" },
    {variable: "harm_outcome_other___5", drug: "other", outcome: "harm", definition: "Related crash without injury" },
    {variable: "harm_outcome_other___6", drug: "other", outcome: "harm", definition: "Related crash with injury" },
    {variable: "harm_outcome_other___7", drug: "other", outcome: "harm", definition: "Related crash resulting in death" },
    {variable: "harm_outcome_other___8", drug: "other", outcome: "harm", definition: "Related crime" },
    {variable: "harm_outcome_other___9", drug: "other", outcome: "harm", definition: "Unrelated crime total" },
    {variable: "harm_outcome_other___10", drug: "other", outcome: "harm", definition: "Driving Under the Influence" },
    {variable: "harm_outcome_other___11", drug: "other", outcome: "harm", definition: "Combined metric or scale" },
    {variable: "harm_outcome_other___12", drug: "other", outcome: "harm", definition: "Age at first use" },
    {variable: "harm_outcome_other___13", drug: "other", outcome: "harm", definition: "Other harm outcome" },
    {variable: "harm_outcome_other___14", drug: "other", outcome: "harm", definition: "Related crash injury unspecified" },

    {variable: "harm_outcome_coffee___1", drug: "coffee", outcome: "harm", definition: "Proportion with substance-related injury within a timeframe" },
    {variable: "harm_outcome_coffee___2", drug: "coffee", outcome: "harm", definition: "Frequency of substance-related injury within a timeframe" },
    {variable: "harm_outcome_coffee___3", drug: "coffee", outcome: "harm", definition: "Related health conditions" },
    {variable: "harm_outcome_coffee___4", drug: "coffee", outcome: "harm", definition: "Related deaths" },
    {variable: "harm_outcome_coffee___5", drug: "coffee", outcome: "harm", definition: "Related crash without injury" },
    {variable: "harm_outcome_coffee___6", drug: "coffee", outcome: "harm", definition: "Related crash with injury" },
    {variable: "harm_outcome_coffee___7", drug: "coffee", outcome: "harm", definition: "Related crash resulting in death" },
    {variable: "harm_outcome_coffee___8", drug: "coffee", outcome: "harm", definition: "Related crime" },
    {variable: "harm_outcome_coffee___9", drug: "coffee", outcome: "harm", definition: "Unrelated crime total" },
    {variable: "harm_outcome_coffee___10", drug: "coffee", outcome: "harm", definition: "Driving Under the Influence" },
    {variable: "harm_outcome_coffee___11", drug: "coffee", outcome: "harm", definition: "Combined metric or scale" },
    {variable: "harm_outcome_coffee___12", drug: "coffee", outcome: "harm", definition: "Age at first use" },
    {variable: "harm_outcome_coffee___13", drug: "coffee", outcome: "harm", definition: "Other harm outcome" },
    {variable: "harm_outcome_coffee___14", drug: "coffee", outcome: "harm", definition: "Related crash injury unspecified" },

    {variable: "harm_outcome_pharma___1", drug: "pharmaceuticals", outcome: "harm", definition: "Proportion with substance-related injury within a timeframe" },
    {variable: "harm_outcome_pharma___2", drug: "pharmaceuticals", outcome: "harm", definition: "Frequency of substance-related injury within a timeframe" },
    {variable: "harm_outcome_pharma___3", drug: "pharmaceuticals", outcome: "harm", definition: "Related health conditions" },
    {variable: "harm_outcome_pharma___4", drug: "pharmaceuticals", outcome: "harm", definition: "Related deaths" },
    {variable: "harm_outcome_pharma___5", drug: "pharmaceuticals", outcome: "harm", definition: "Related crash without injury" },
    {variable: "harm_outcome_pharma___6", drug: "pharmaceuticals", outcome: "harm", definition: "Related crash with injury" },
    {variable: "harm_outcome_pharma___7", drug: "pharmaceuticals", outcome: "harm", definition: "Related crash resulting in death" },
    {variable: "harm_outcome_pharma___8", drug: "pharmaceuticals", outcome: "harm", definition: "Related crime" },
    {variable: "harm_outcome_pharma___9", drug: "pharmaceuticals", outcome: "harm", definition: "Unrelated crime total" },
    {variable: "harm_outcome_pharma___10", drug: "pharmaceuticals", outcome: "harm", definition: "Driving Under the Influence" },
    {variable: "harm_outcome_pharma___11", drug: "pharmaceuticals", outcome: "harm", definition: "Combined metric or scale" },
    {variable: "harm_outcome_pharma___12", drug: "pharmaceuticals", outcome: "harm", definition: "Age at first use" },
    {variable: "harm_outcome_pharma___13", drug: "pharmaceuticals", outcome: "harm", definition: "Other harm outcome" },
    {variable: "harm_outcome_pharma___14", drug: "pharmaceuticals", outcome: "harm", definition: "Related crash injury unspecified" },

    {variable: "harm_outcome_depress___1", drug: "depressant", outcome: "harm", definition: "Proportion with substance-related injury within a timeframe" },
    {variable: "harm_outcome_depress___2", drug: "depressant", outcome: "harm", definition: "Frequency of substance-related injury within a timeframe" },
    {variable: "harm_outcome_depress___3", drug: "depressant", outcome: "harm", definition: "Related health conditions" },
    {variable: "harm_outcome_depress___4", drug: "depressant", outcome: "harm", definition: "Related deaths" },
    {variable: "harm_outcome_depress___5", drug: "depressant", outcome: "harm", definition: "Related crash without injury" },
    {variable: "harm_outcome_depress___6", drug: "depressant", outcome: "harm", definition: "Related crash with injury" },
    {variable: "harm_outcome_depress___7", drug: "depressant", outcome: "harm", definition: "Related crash resulting in death" },
    {variable: "harm_outcome_depress___8", drug: "depressant", outcome: "harm", definition: "Related crime" },
    {variable: "harm_outcome_depress___9", drug: "depressant", outcome: "harm", definition: "Unrelated crime total" },
    {variable: "harm_outcome_depress___10", drug: "depressant", outcome: "harm", definition: "Driving Under the Influence" },
    {variable: "harm_outcome_depress___11", drug: "depressant", outcome: "harm", definition: "Combined metric or scale" },
    {variable: "harm_outcome_depress___12", drug: "depressant", outcome: "harm", definition: "Age at first use" },
    {variable: "harm_outcome_depress___13", drug: "depressant", outcome: "harm", definition: "Other harm outcome" },
    {variable: "harm_outcome_depress___14", drug: "depressant", outcome: "harm", definition: "Related crash injury unspecified" },

    {variable: "harm_outcome_ped___1", drug: "performance enhancing drug", outcome: "harm", definition: "Proportion with substance-related injury within a timeframe" },
    {variable: "harm_outcome_ped___2", drug: "performance enhancing drug", outcome: "harm", definition: "Frequency of substance-related injury within a timeframe" },
    {variable: "harm_outcome_ped___3", drug: "performance enhancing drug", outcome: "harm", definition: "Related health conditions" },
    {variable: "harm_outcome_ped___4", drug: "performance enhancing drug", outcome: "harm", definition: "Related deaths" },
    {variable: "harm_outcome_ped___5", drug: "performance enhancing drug", outcome: "harm", definition: "Related crash without injury" },
    {variable: "harm_outcome_ped___6", drug: "performance enhancing drug", outcome: "harm", definition: "Related crash with injury" },
    {variable: "harm_outcome_ped___7", drug: "performance enhancing drug", outcome: "harm", definition: "Related crash resulting in death" },
    {variable: "harm_outcome_ped___8", drug: "performance enhancing drug", outcome: "harm", definition: "Related crime" },
    {variable: "harm_outcome_ped___9", drug: "performance enhancing drug", outcome: "harm", definition: "Unrelated crime total" },
    {variable: "harm_outcome_ped___10", drug: "performance enhancing drug", outcome: "harm", definition: "Driving Under the Influence" },
    {variable: "harm_outcome_ped___11", drug: "performance enhancing drug", outcome: "harm", definition: "Combined metric or scale" },
    {variable: "harm_outcome_ped___12", drug: "performance enhancing drug", outcome: "harm", definition: "Age at first use" },
    {variable: "harm_outcome_ped___13", drug: "performance enhancing drug", outcome: "harm", definition: "Other harm outcome" },
    {variable: "harm_outcome_ped___14", drug: "performance enhancing drug", outcome: "harm", definition: "Related crash injury unspecified" },

    {variable: "harm_outcome_opioid___1", drug: "opioid", outcome: "harm", definition: "Proportion with substance-related injury within a timeframe" },
    {variable: "harm_outcome_opioid___2", drug: "opioid", outcome: "harm", definition: "Frequency of substance-related injury within a timeframe" },
    {variable: "harm_outcome_opioid___3", drug: "opioid", outcome: "harm", definition: "Related health conditions" },
    {variable: "harm_outcome_opioid___4", drug: "opioid", outcome: "harm", definition: "Related deaths" },
    {variable: "harm_outcome_opioid___5", drug: "opioid", outcome: "harm", definition: "Related crash without injury" },
    {variable: "harm_outcome_opioid___6", drug: "opioid", outcome: "harm", definition: "Related crash with injury" },
    {variable: "harm_outcome_opioid___7", drug: "opioid", outcome: "harm", definition: "Related crash resulting in death" },
    {variable: "harm_outcome_opioid___8", drug: "opioid", outcome: "harm", definition: "Related crime" },
    {variable: "harm_outcome_opioid___9", drug: "opioid", outcome: "harm", definition: "Unrelated crime total" },
    {variable: "harm_outcome_opioid___10", drug: "opioid", outcome: "harm", definition: "Driving Under the Influence" },
    {variable: "harm_outcome_opioid___11", drug: "opioid", outcome: "harm", definition: "Combined metric or scale" },
    {variable: "harm_outcome_opioid___12", drug: "opioid", outcome: "harm", definition: "Age at first use" },
    {variable: "harm_outcome_opioid___13", drug: "opioid", outcome: "harm", definition: "Other harm outcome" },
    {variable: "harm_outcome_opioid___14", drug: "opioid", outcome: "harm", definition: "Related crash injury unspecified" },

    {variable: "harm_outcome_inhalant___1", drug: "inhalant", outcome: "harm", definition: "Proportion with substance-related injury within a timeframe" },
    {variable: "harm_outcome_inhalant___2", drug: "inhalant", outcome: "harm", definition: "Frequency of substance-related injury within a timeframe" },
    {variable: "harm_outcome_inhalant___3", drug: "inhalant", outcome: "harm", definition: "Related health conditions" },
    {variable: "harm_outcome_inhalant___4", drug: "inhalant", outcome: "harm", definition: "Related deaths" },
    {variable: "harm_outcome_inhalant___5", drug: "inhalant", outcome: "harm", definition: "Related crash without injury" },
    {variable: "harm_outcome_inhalant___6", drug: "inhalant", outcome: "harm", definition: "Related crash with injury" },
    {variable: "harm_outcome_inhalant___7", drug: "inhalant", outcome: "harm", definition: "Related crash resulting in death" },
    {variable: "harm_outcome_inhalant___8", drug: "inhalant", outcome: "harm", definition: "Related crime" },
    {variable: "harm_outcome_inhalant___9", drug: "inhalant", outcome: "harm", definition: "Unrelated crime total" },
    {variable: "harm_outcome_inhalant___10", drug: "inhalant", outcome: "harm", definition: "Driving Under the Influence" },
    {variable: "harm_outcome_inhalant___11", drug: "inhalant", outcome: "harm", definition: "Combined metric or scale" },
    {variable: "harm_outcome_inhalant___12", drug: "inhalant", outcome: "harm", definition: "Age at first use" },
    {variable: "harm_outcome_inhalant___13", drug: "inhalant", outcome: "harm", definition: "Other harm outcome" },
    {variable: "harm_outcome_inhalant___14", drug: "inhalant", outcome: "harm", definition: "Related crash injury unspecified" },

    {variable: "harm_outcome_alcohol___1", drug: "alcohol", outcome: "harm", definition: "Proportion with substance-related injury within a timeframe" },
    {variable: "harm_outcome_alcohol___2", drug: "alcohol", outcome: "harm", definition: "Frequency of substance-related injury within a timeframe" },
    {variable: "harm_outcome_alcohol___3", drug: "alcohol", outcome: "harm", definition: "Related health conditions" },
    {variable: "harm_outcome_alcohol___4", drug: "alcohol", outcome: "harm", definition: "Related deaths" },
    {variable: "harm_outcome_alcohol___5", drug: "alcohol", outcome: "harm", definition: "Related crash without injury" },
    {variable: "harm_outcome_alcohol___6", drug: "alcohol", outcome: "harm", definition: "Related crash with injury" },
    {variable: "harm_outcome_alcohol___7", drug: "alcohol", outcome: "harm", definition: "Related crash resulting in death" },
    {variable: "harm_outcome_alcohol___8", drug: "alcohol", outcome: "harm", definition: "Related crime" },
    {variable: "harm_outcome_alcohol___9", drug: "alcohol", outcome: "harm", definition: "Unrelated crime total" },
    {variable: "harm_outcome_alcohol___10", drug: "alcohol", outcome: "harm", definition: "Driving Under the Influence" },
    {variable: "harm_outcome_alcohol___11", drug: "alcohol", outcome: "harm", definition: "Combined metric or scale" },
    {variable: "harm_outcome_alcohol___12", drug: "alcohol", outcome: "harm", definition: "Age at first use" },
    {variable: "harm_outcome_alcohol___13", drug: "alcohol", outcome: "harm", definition: "Other harm outcome" },
    {variable: "harm_outcome_alcohol___14", drug: "alcohol", outcome: "harm", definition: "Related crash injury unspecified" },

    {variable: "harm_outcome_cocaine___1", drug: "cocaine", outcome: "harm", definition: "Proportion with substance-related injury within a timeframe" },
    {variable: "harm_outcome_cocaine___2", drug: "cocaine", outcome: "harm", definition: "Frequency of substance-related injury within a timeframe" },
    {variable: "harm_outcome_cocaine___3", drug: "cocaine", outcome: "harm", definition: "Related health conditions" },
    {variable: "harm_outcome_cocaine___4", drug: "cocaine", outcome: "harm", definition: "Related deaths" },
    {variable: "harm_outcome_cocaine___5", drug: "cocaine", outcome: "harm", definition: "Related crash without injury" },
    {variable: "harm_outcome_cocaine___6", drug: "cocaine", outcome: "harm", definition: "Related crash with injury" },
    {variable: "harm_outcome_cocaine___7", drug: "cocaine", outcome: "harm", definition: "Related crash resulting in death" },
    {variable: "harm_outcome_cocaine___8", drug: "cocaine", outcome: "harm", definition: "Related crime" },
    {variable: "harm_outcome_cocaine___9", drug: "cocaine", outcome: "harm", definition: "Unrelated crime total" },
    {variable: "harm_outcome_cocaine___10", drug: "cocaine", outcome: "harm", definition: "Driving Under the Influence" },
    {variable: "harm_outcome_cocaine___11", drug: "cocaine", outcome: "harm", definition: "Combined metric or scale" },
    {variable: "harm_outcome_cocaine___12", drug: "cocaine", outcome: "harm", definition: "Age at first use" },
    {variable: "harm_outcome_cocaine___13", drug: "cocaine", outcome: "harm", definition: "Other harm outcome" },
    {variable: "harm_outcome_cocaine___14", drug: "cocaine", outcome: "harm", definition: "Related crash injury unspecified" },

    {variable: "harm_outcome_e___1", drug: "ecstacy", outcome: "harm", definition: "Proportion with substance-related injury within a timeframe" },
    {variable: "harm_outcome_e___2", drug: "ecstacy", outcome: "harm", definition: "Frequency of substance-related injury within a timeframe" },
    {variable: "harm_outcome_e___3", drug: "ecstacy", outcome: "harm", definition: "Related health conditions" },
    {variable: "harm_outcome_e___4", drug: "ecstacy", outcome: "harm", definition: "Related deaths" },
    {variable: "harm_outcome_e___5", drug: "ecstacy", outcome: "harm", definition: "Related crash without injury" },
    {variable: "harm_outcome_e___6", drug: "ecstacy", outcome: "harm", definition: "Related crash with injury" },
    {variable: "harm_outcome_e___7", drug: "ecstacy", outcome: "harm", definition: "Related crash resulting in death" },
    {variable: "harm_outcome_e___8", drug: "ecstacy", outcome: "harm", definition: "Related crime" },
    {variable: "harm_outcome_e___9", drug: "ecstacy", outcome: "harm", definition: "Unrelated crime total" },
    {variable: "harm_outcome_e___10", drug: "ecstacy", outcome: "harm", definition: "Driving Under the Influence" },
    {variable: "harm_outcome_e___11", drug: "ecstacy", outcome: "harm", definition: "Combined metric or scale" },
    {variable: "harm_outcome_e___12", drug: "ecstacy", outcome: "harm", definition: "Age at first use" },
    {variable: "harm_outcome_e___13", drug: "ecstacy", outcome: "harm", definition: "Other harm outcome" },
    {variable: "harm_outcome_e___14", drug: "ecstacy", outcome: "harm", definition: "Related crash injury unspecified" },

    {variable: "harm_outcome_meth___1", drug: "meth", outcome: "harm", definition: "Proportion with substance-related injury within a timeframe" },
    {variable: "harm_outcome_meth___2", drug: "meth", outcome: "harm", definition: "Frequency of substance-related injury within a timeframe" },
    {variable: "harm_outcome_meth___3", drug: "meth", outcome: "harm", definition: "Related health conditions" },
    {variable: "harm_outcome_meth___4", drug: "meth", outcome: "harm", definition: "Related deaths" },
    {variable: "harm_outcome_meth___5", drug: "meth", outcome: "harm", definition: "Related crash without injury" },
    {variable: "harm_outcome_meth___6", drug: "meth", outcome: "harm", definition: "Related crash with injury" },
    {variable: "harm_outcome_meth___7", drug: "meth", outcome: "harm", definition: "Related crash resulting in death" },
    {variable: "harm_outcome_meth___8", drug: "meth", outcome: "harm", definition: "Related crime" },
    {variable: "harm_outcome_meth___9", drug: "meth", outcome: "harm", definition: "Unrelated crime total" },
    {variable: "harm_outcome_meth___10", drug: "meth", outcome: "harm", definition: "Driving Under the Influence" },
    {variable: "harm_outcome_meth___11", drug: "meth", outcome: "harm", definition: "Combined metric or scale" },
    {variable: "harm_outcome_meth___12", drug: "meth", outcome: "harm", definition: "Age at first use" },
    {variable: "harm_outcome_meth___13", drug: "meth", outcome: "harm", definition: "Other harm outcome" },
    {variable: "harm_outcome_meth___14", drug: "meth", outcome: "harm", definition: "Related crash injury unspecified" },

    {variable: "harm_outcome_cannabis___1", drug: "cannabis", outcome: "harm", definition: "Proportion with substance-related injury within a timeframe" },
    {variable: "harm_outcome_cannabis___2", drug: "cannabis", outcome: "harm", definition: "Frequency of substance-related injury within a timeframe" },
    {variable: "harm_outcome_cannabis___3", drug: "cannabis", outcome: "harm", definition: "Related health conditions" },
    {variable: "harm_outcome_cannabis___4", drug: "cannabis", outcome: "harm", definition: "Related deaths" },
    {variable: "harm_outcome_cannabis___5", drug: "cannabis", outcome: "harm", definition: "Related crash without injury" },
    {variable: "harm_outcome_cannabis___6", drug: "cannabis", outcome: "harm", definition: "Related crash with injury" },
    {variable: "harm_outcome_cannabis___7", drug: "cannabis", outcome: "harm", definition: "Related crash resulting in death" },
    {variable: "harm_outcome_cannabis___8", drug: "cannabis", outcome: "harm", definition: "Related crime" },
    {variable: "harm_outcome_cannabis___9", drug: "cannabis", outcome: "harm", definition: "Unrelated crime total" },
    {variable: "harm_outcome_cannabis___10", drug: "cannabis", outcome: "harm", definition: "Driving Under the Influence" },
    {variable: "harm_outcome_cannabis___11", drug: "cannabis", outcome: "harm", definition: "Combined metric or scale" },
    {variable: "harm_outcome_cannabis___12", drug: "cannabis", outcome: "harm", definition: "Age at first use" },
    {variable: "harm_outcome_cannabis___13", drug: "cannabis", outcome: "harm", definition: "Other harm outcome" },
    {variable: "harm_outcome_cannabis___14", drug: "cannabis", outcome: "harm", definition: "Related crash injury unspecified" },

    {variable: "harm_outcome_vapes___1", drug: "vapes", outcome: "harm", definition: "Proportion with substance-related injury within a timeframe" },
    {variable: "harm_outcome_vapes___2", drug: "vapes", outcome: "harm", definition: "Frequency of substance-related injury within a timeframe" },
    {variable: "harm_outcome_vapes___3", drug: "vapes", outcome: "harm", definition: "Related health conditions" },
    {variable: "harm_outcome_vapes___4", drug: "vapes", outcome: "harm", definition: "Related deaths" },
    {variable: "harm_outcome_vapes___5", drug: "vapes", outcome: "harm", definition: "Related crash without injury" },
    {variable: "harm_outcome_vapes___6", drug: "vapes", outcome: "harm", definition: "Related crash with injury" },
    {variable: "harm_outcome_vapes___7", drug: "vapes", outcome: "harm", definition: "Related crash resulting in death" },
    {variable: "harm_outcome_vapes___8", drug: "vapes", outcome: "harm", definition: "Related crime" },
    {variable: "harm_outcome_vapes___9", drug: "vapes", outcome: "harm", definition: "Unrelated crime total" },
    {variable: "harm_outcome_vapes___10", drug: "vapes", outcome: "harm", definition: "Driving Under the Influence" },
    {variable: "harm_outcome_vapes___11", drug: "vapes", outcome: "harm", definition: "Combined metric or scale" },
    {variable: "harm_outcome_vapes___12", drug: "vapes", outcome: "harm", definition: "Age at first use" },
    {variable: "harm_outcome_vapes___13", drug: "vapes", outcome: "harm", definition: "Other harm outcome" },
    {variable: "harm_outcome_vapes___14", drug: "vapes", outcome: "harm", definition: "Related crash injury unspecified" },

    {variable: "harm_outcome_smokeless___1", drug: "smokeless", outcome: "harm", definition: "Proportion with substance-related injury within a timeframe" },
    {variable: "harm_outcome_smokeless___2", drug: "smokeless", outcome: "harm", definition: "Frequency of substance-related injury within a timeframe" },
    {variable: "harm_outcome_smokeless___3", drug: "smokeless", outcome: "harm", definition: "Related health conditions" },
    {variable: "harm_outcome_smokeless___4", drug: "smokeless", outcome: "harm", definition: "Related deaths" },
    {variable: "harm_outcome_smokeless___5", drug: "smokeless", outcome: "harm", definition: "Related crash without injury" },
    {variable: "harm_outcome_smokeless___6", drug: "smokeless", outcome: "harm", definition: "Related crash with injury" },
    {variable: "harm_outcome_smokeless___7", drug: "smokeless", outcome: "harm", definition: "Related crash resulting in death" },
    {variable: "harm_outcome_smokeless___8", drug: "smokeless", outcome: "harm", definition: "Related crime" },
    {variable: "harm_outcome_smokeless___9", drug: "smokeless", outcome: "harm", definition: "Unrelated crime total" },
    {variable: "harm_outcome_smokeless___10", drug: "smokeless", outcome: "harm", definition: "Driving Under the Influence" },
    {variable: "harm_outcome_smokeless___11", drug: "smokeless", outcome: "harm", definition: "Combined metric or scale" },
    {variable: "harm_outcome_smokeless___12", drug: "smokeless", outcome: "harm", definition: "Age at first use" },
    {variable: "harm_outcome_smokeless___13", drug: "smokeless", outcome: "harm", definition: "Other harm outcome" },
    {variable: "harm_outcome_smokeless___14", drug: "smokeless", outcome: "harm", definition: "Related crash injury unspecified" },

    {variable: "harm_outcome_cigarette___1", drug: "cigarette", outcome: "harm", definition: "Proportion with substance-related injury within a timeframe" },
    {variable: "harm_outcome_cigarette___2", drug: "cigarette", outcome: "harm", definition: "Frequency of substance-related injury within a timeframe" },
    {variable: "harm_outcome_cigarette___3", drug: "cigarette", outcome: "harm", definition: "Related health conditions" },
    {variable: "harm_outcome_cigarette___4", drug: "cigarette", outcome: "harm", definition: "Related deaths" },
    {variable: "harm_outcome_cigarette___5", drug: "cigarette", outcome: "harm", definition: "Related crash without injury" },
    {variable: "harm_outcome_cigarette___6", drug: "cigarette", outcome: "harm", definition: "Related crash with injury" },
    {variable: "harm_outcome_cigarette___7", drug: "cigarette", outcome: "harm", definition: "Related crash resulting in death" },
    {variable: "harm_outcome_cigarette___8", drug: "cigarette", outcome: "harm", definition: "Related crime" },
    {variable: "harm_outcome_cigarette___9", drug: "cigarette", outcome: "harm", definition: "Unrelated crime total" },
    {variable: "harm_outcome_cigarette___10", drug: "cigarette", outcome: "harm", definition: "Driving Under the Influence" },
    {variable: "harm_outcome_cigarette___11", drug: "cigarette", outcome: "harm", definition: "Combined metric or scale" },
    {variable: "harm_outcome_cigarette___12", drug: "cigarette", outcome: "harm", definition: "Age at first use" },
    {variable: "harm_outcome_cigarette___13", drug: "cigarette", outcome: "harm", definition: "Other harm outcome" },
    {variable: "harm_outcome_cigarette___14", drug: "cigarette", outcome: "harm", definition: "Related crash injury unspecified" },

    {variable: "harm_outcome_second___1", drug: "second", outcome: "harm", definition: "Proportion with substance-related injury within a timeframe" },
    {variable: "harm_outcome_second___2", drug: "second", outcome: "harm", definition: "Frequency of substance-related injury within a timeframe" },
    {variable: "harm_outcome_second___3", drug: "second", outcome: "harm", definition: "Related health conditions" },
    {variable: "harm_outcome_second___4", drug: "second", outcome: "harm", definition: "Related deaths" },
    {variable: "harm_outcome_second___5", drug: "second", outcome: "harm", definition: "Related crash without injury" },
    {variable: "harm_outcome_second___6", drug: "second", outcome: "harm", definition: "Related crash with injury" },
    {variable: "harm_outcome_second___7", drug: "second", outcome: "harm", definition: "Related crash resulting in death" },
    {variable: "harm_outcome_second___8", drug: "second", outcome: "harm", definition: "Related crime" },
    {variable: "harm_outcome_second___9", drug: "second", outcome: "harm", definition: "Unrelated crime total" },
    {variable: "harm_outcome_second___10", drug: "second", outcome: "harm", definition: "Driving Under the Influence" },
    {variable: "harm_outcome_second___11", drug: "second", outcome: "harm", definition: "Combined metric or scale" },
    {variable: "harm_outcome_second___12", drug: "second", outcome: "harm", definition: "Age at first use" },
    {variable: "harm_outcome_second___13", drug: "second", outcome: "harm", definition: "Other harm outcome" },
    {variable: "harm_outcome_second___14", drug: "second", outcome: "harm", definition: "Related crash injury unspecified" },

    {variable: "behav_outcome_alcohol___1", drug: "alcohol", outcome: "harm", definition: "Proportion with substance-related injury within a timeframe" },
    {variable: "behav_outcome_alcohol___2", drug: "alcohol", outcome: "harm", definition: "Frequency of substance-related injury within a timeframe" },
    {variable: "behav_outcome_alcohol___3", drug: "alcohol", outcome: "harm", definition: "Related health conditions" },
    {variable: "behav_outcome_alcohol___4", drug: "alcohol", outcome: "harm", definition: "Related deaths" },
    {variable: "behav_outcome_alcohol___5", drug: "alcohol", outcome: "harm", definition: "Related crash without injury" },
    {variable: "behav_outcome_alcohol___6", drug: "alcohol", outcome: "harm", definition: "Related crash with injury" },
    {variable: "behav_outcome_alcohol___7", drug: "alcohol", outcome: "harm", definition: "Related crash resulting in death" },
    {variable: "behav_outcome_alcohol___8", drug: "alcohol", outcome: "harm", definition: "Related crime" },
    {variable: "behav_outcome_alcohol___9", drug: "alcohol", outcome: "harm", definition: "Unrelated crime total" },
    {variable: "behav_outcome_alcohol___10", drug: "alcohol", outcome: "harm", definition: "Driving Under the Influence" },
    {variable: "behav_outcome_alcohol___11", drug: "alcohol", outcome: "harm", definition: "Combined metric or scale" },
    {variable: "behav_outcome_alcohol___12", drug: "alcohol", outcome: "harm", definition: "Age at first use" },
    {variable: "behav_outcome_alcohol___13", drug: "alcohol", outcome: "harm", definition: "Other harm outcome" },
    {variable: "behav_outcome_alcohol___14", drug: "alcohol", outcome: "harm", definition: "Related crash injury unspecified" },

    {variable: "behav_outcome_coffee___1", drug: "coffee", outcome: "behaviour", definition: "Unlawful supply / Refusal of service"},
    {variable: "behav_outcome_coffee___2", drug: "coffee", outcome: "behaviour", definition: "Unlawfully purchased / obtained"},
    {variable: "behav_outcome_coffee___3", drug: "coffee", outcome: "behaviour", definition: "Intentions and attitudes"},
    {variable: "behav_outcome_coffee___4", drug: "coffee", outcome: "behaviour", definition: "Desire to quit"},
    {variable: "behav_outcome_coffee___5", drug: "coffee", outcome: "behaviour", definition: "Peer related factors"},
    {variable: "behav_outcome_coffee___6", drug: "coffee", outcome: "behaviour", definition: "Knowledge, awareness or confidence"},
    {variable: "behav_outcome_coffee___7", drug: "coffee", outcome: "behaviour", definition: "Parenting"},
    {variable: "behav_outcome_coffee___8", drug: "coffee", outcome: "behaviour", definition: "Accessibility"},
    {variable: "behav_outcome_coffee___9", drug: "coffee", outcome: "behaviour", definition: "Self efficacy"},

    {variable: "behav_outcome_pharma___1", drug: "pharmaceuticals", outcome: "behaviour", definition: "Unlawful supply / Refusal of service"},
    {variable: "behav_outcome_pharma___2", drug: "pharmaceuticals", outcome: "behaviour", definition: "Unlawfully purchased / obtained"},
    {variable: "behav_outcome_pharma___3", drug: "pharmaceuticals", outcome: "behaviour", definition: "Intentions and attitudes"},
    {variable: "behav_outcome_pharma___4", drug: "pharmaceuticals", outcome: "behaviour", definition: "Desire to quit"},
    {variable: "behav_outcome_pharma___5", drug: "pharmaceuticals", outcome: "behaviour", definition: "Peer related factors"},
    {variable: "behav_outcome_pharma___6", drug: "pharmaceuticals", outcome: "behaviour", definition: "Knowledge, awareness or confidence"},
    {variable: "behav_outcome_pharma___7", drug: "pharmaceuticals", outcome: "behaviour", definition: "Parenting"},
    {variable: "behav_outcome_pharma___8", drug: "pharmaceuticals", outcome: "behaviour", definition: "Accessibility"},
    {variable: "behav_outcome_pharma___9", drug: "pharmaceuticals", outcome: "behaviour", definition: "Self efficacy"},

    {variable: "behav_outcome_depress___1", drug: "depressant", outcome: "behaviour", definition: "Unlawful supply / Refusal of service"},
    {variable: "behav_outcome_depress___2", drug: "depressant", outcome: "behaviour", definition: "Unlawfully purchased / obtained"},
    {variable: "behav_outcome_depress___3", drug: "depressant", outcome: "behaviour", definition: "Intentions and attitudes"},
    {variable: "behav_outcome_depress___4", drug: "depressant", outcome: "behaviour", definition: "Desire to quit"},
    {variable: "behav_outcome_depress___5", drug: "depressant", outcome: "behaviour", definition: "Peer related factors"},
    {variable: "behav_outcome_depress___6", drug: "depressant", outcome: "behaviour", definition: "Knowledge, awareness or confidence"},
    {variable: "behav_outcome_depress___7", drug: "depressant", outcome: "behaviour", definition: "Parenting"},
    {variable: "behav_outcome_depress___8", drug: "depressant", outcome: "behaviour", definition: "Accessibility"},
    {variable: "behav_outcome_depress___9", drug: "depressant", outcome: "behaviour", definition: "Self efficacy"},

    {variable: "behav_outcome_hall___1", drug: "hallucinogen", outcome: "behaviour", definition: "Unlawful supply / Refusal of service"},
    {variable: "behav_outcome_hall___2", drug: "hallucinogen", outcome: "behaviour", definition: "Unlawfully purchased / obtained"},
    {variable: "behav_outcome_hall___3", drug: "hallucinogen", outcome: "behaviour", definition: "Intentions and attitudes"},
    {variable: "behav_outcome_hall___4", drug: "hallucinogen", outcome: "behaviour", definition: "Desire to quit"},
    {variable: "behav_outcome_hall___5", drug: "hallucinogen", outcome: "behaviour", definition: "Peer related factors"},
    {variable: "behav_outcome_hall___6", drug: "hallucinogen", outcome: "behaviour", definition: "Knowledge, awareness or confidence"},
    {variable: "behav_outcome_hall___7", drug: "hallucinogen", outcome: "behaviour", definition: "Parenting"},
    {variable: "behav_outcome_hall___8", drug: "hallucinogen", outcome: "behaviour", definition: "Accessibility"},
    {variable: "behav_outcome_hall___9", drug: "hallucinogen", outcome: "behaviour", definition: "Self efficacy"},

    {variable: "behav_outcome_ped___1", drug: "performance enhancing drug", outcome: "behaviour", definition: "Unlawful supply / Refusal of service"},
    {variable: "behav_outcome_ped___2", drug: "performance enhancing drug", outcome: "behaviour", definition: "Unlawfully purchased / obtained"},
    {variable: "behav_outcome_ped___3", drug: "performance enhancing drug", outcome: "behaviour", definition: "Intentions and attitudes"},
    {variable: "behav_outcome_ped___4", drug: "performance enhancing drug", outcome: "behaviour", definition: "Desire to quit"},
    {variable: "behav_outcome_ped___5", drug: "performance enhancing drug", outcome: "behaviour", definition: "Peer related factors"},
    {variable: "behav_outcome_ped___6", drug: "performance enhancing drug", outcome: "behaviour", definition: "Knowledge, awareness or confidence"},
    {variable: "behav_outcome_ped___7", drug: "performance enhancing drug", outcome: "behaviour", definition: "Parenting"},
    {variable: "behav_outcome_ped___8", drug: "performance enhancing drug", outcome: "behaviour", definition: "Accessibility"},
    {variable: "behav_outcome_ped___9", drug: "performance enhancing drug", outcome: "behaviour", definition: "Self efficacy"},

    {variable: "behav_outcome_opioid___1", drug: "opioid", outcome: "behaviour", definition: "Unlawful supply / Refusal of service"},
    {variable: "behav_outcome_opioid___2", drug: "opioid", outcome: "behaviour", definition: "Unlawfully purchased / obtained"},
    {variable: "behav_outcome_opioid___3", drug: "opioid", outcome: "behaviour", definition: "Intentions and attitudes"},
    {variable: "behav_outcome_opioid___4", drug: "opioid", outcome: "behaviour", definition: "Desire to quit"},
    {variable: "behav_outcome_opioid___5", drug: "opioid", outcome: "behaviour", definition: "Peer related factors"},
    {variable: "behav_outcome_opioid___6", drug: "opioid", outcome: "behaviour", definition: "Knowledge, awareness or confidence"},
    {variable: "behav_outcome_opioid___7", drug: "opioid", outcome: "behaviour", definition: "Parenting"},
    {variable: "behav_outcome_opioid___8", drug: "opioid", outcome: "behaviour", definition: "Accessibility"},
    {variable: "behav_outcome_opioid___9", drug: "opioid", outcome: "behaviour", definition: "Self efficacy"},

    {variable: "behav_outcome_inhalant___1", drug: "inhalant", outcome: "behaviour", definition: "Unlawful supply / Refusal of service"},
    {variable: "behav_outcome_inhalant___2", drug: "inhalant", outcome: "behaviour", definition: "Unlawfully purchased / obtained"},
    {variable: "behav_outcome_inhalant___3", drug: "inhalant", outcome: "behaviour", definition: "Intentions and attitudes"},
    {variable: "behav_outcome_inhalant___4", drug: "inhalant", outcome: "behaviour", definition: "Desire to quit"},
    {variable: "behav_outcome_inhalant___5", drug: "inhalant", outcome: "behaviour", definition: "Peer related factors"},
    {variable: "behav_outcome_inhalant___6", drug: "inhalant", outcome: "behaviour", definition: "Knowledge, awareness or confidence"},
    {variable: "behav_outcome_inhalant___7", drug: "inhalant", outcome: "behaviour", definition: "Parenting"},
    {variable: "behav_outcome_inhalant___8", drug: "inhalant", outcome: "behaviour", definition: "Accessibility"},
    {variable: "behav_outcome_inhalant___9", drug: "inhalant", outcome: "behaviour", definition: "Self efficacy"},

    {variable: "behav_outcome_cocaine___1", drug: "cocaine", outcome: "behaviour", definition: "Unlawful supply / Refusal of service"},
    {variable: "behav_outcome_cocaine___2", drug: "cocaine", outcome: "behaviour", definition: "Unlawfully purchased / obtained"},
    {variable: "behav_outcome_cocaine___3", drug: "cocaine", outcome: "behaviour", definition: "Intentions and attitudes"},
    {variable: "behav_outcome_cocaine___4", drug: "cocaine", outcome: "behaviour", definition: "Desire to quit"},
    {variable: "behav_outcome_cocaine___5", drug: "cocaine", outcome: "behaviour", definition: "Peer related factors"},
    {variable: "behav_outcome_cocaine___6", drug: "cocaine", outcome: "behaviour", definition: "Knowledge, awareness or confidence"},
    {variable: "behav_outcome_cocaine___7", drug: "cocaine", outcome: "behaviour", definition: "Parenting"},
    {variable: "behav_outcome_cocaine___8", drug: "cocaine", outcome: "behaviour", definition: "Accessibility"},
    {variable: "behav_outcome_cocaine___9", drug: "cocaine", outcome: "behaviour", definition: "Self efficacy"},

    {variable: "behav_outcome_e___1", drug: "ecstacy", outcome: "behaviour", definition: "Unlawful supply / Refusal of service"},
    {variable: "behav_outcome_e___2", drug: "ecstacy", outcome: "behaviour", definition: "Unlawfully purchased / obtained"},
    {variable: "behav_outcome_e___3", drug: "ecstacy", outcome: "behaviour", definition: "Intentions and attitudes"},
    {variable: "behav_outcome_e___4", drug: "ecstacy", outcome: "behaviour", definition: "Desire to quit"},
    {variable: "behav_outcome_e___5", drug: "ecstacy", outcome: "behaviour", definition: "Peer related factors"},
    {variable: "behav_outcome_e___6", drug: "ecstacy", outcome: "behaviour", definition: "Knowledge, awareness or confidence"},
    {variable: "behav_outcome_e___7", drug: "ecstacy", outcome: "behaviour", definition: "Parenting"},
    {variable: "behav_outcome_e___8", drug: "ecstacy", outcome: "behaviour", definition: "Accessibility"},
    {variable: "behav_outcome_e___9", drug: "ecstacy", outcome: "behaviour", definition: "Self efficacy"},

    {variable: "behav_outcome_meth___1", drug: "meth", outcome: "behaviour", definition: "Unlawful supply / Refusal of service"},
    {variable: "behav_outcome_meth___2", drug: "meth", outcome: "behaviour", definition: "Unlawfully purchased / obtained"},
    {variable: "behav_outcome_meth___3", drug: "meth", outcome: "behaviour", definition: "Intentions and attitudes"},
    {variable: "behav_outcome_meth___4", drug: "meth", outcome: "behaviour", definition: "Desire to quit"},
    {variable: "behav_outcome_meth___5", drug: "meth", outcome: "behaviour", definition: "Peer related factors"},
    {variable: "behav_outcome_meth___6", drug: "meth", outcome: "behaviour", definition: "Knowledge, awareness or confidence"},
    {variable: "behav_outcome_meth___7", drug: "meth", outcome: "behaviour", definition: "Parenting"},
    {variable: "behav_outcome_meth___8", drug: "meth", outcome: "behaviour", definition: "Accessibility"},
    {variable: "behav_outcome_meth___9", drug: "meth", outcome: "behaviour", definition: "Self efficacy"},

    {variable: "behav_outcome_cannabis___1", drug: "cannabis", outcome: "behaviour", definition: "Unlawful supply / Refusal of service"},
    {variable: "behav_outcome_cannabis___2", drug: "cannabis", outcome: "behaviour", definition: "Unlawfully purchased / obtained"},
    {variable: "behav_outcome_cannabis___3", drug: "cannabis", outcome: "behaviour", definition: "Intentions and attitudes"},
    {variable: "behav_outcome_cannabis___4", drug: "cannabis", outcome: "behaviour", definition: "Desire to quit"},
    {variable: "behav_outcome_cannabis___5", drug: "cannabis", outcome: "behaviour", definition: "Peer related factors"},
    {variable: "behav_outcome_cannabis___6", drug: "cannabis", outcome: "behaviour", definition: "Knowledge, awareness or confidence"},
    {variable: "behav_outcome_cannabis___7", drug: "cannabis", outcome: "behaviour", definition: "Parenting"},
    {variable: "behav_outcome_cannabis___8", drug: "cannabis", outcome: "behaviour", definition: "Accessibility"},
    {variable: "behav_outcome_cannabis___9", drug: "cannabis", outcome: "behaviour", definition: "Self efficacy"},

    {variable: "behav_outcome_vapes___1", drug: "vapes", outcome: "behaviour", definition: "Unlawful supply / Refusal of service"},
    {variable: "behav_outcome_vapes___2", drug: "vapes", outcome: "behaviour", definition: "Unlawfully purchased / obtained"},
    {variable: "behav_outcome_vapes___3", drug: "vapes", outcome: "behaviour", definition: "Intentions and attitudes"},
    {variable: "behav_outcome_vapes___4", drug: "vapes", outcome: "behaviour", definition: "Desire to quit"},
    {variable: "behav_outcome_vapes___5", drug: "vapes", outcome: "behaviour", definition: "Peer related factors"},
    {variable: "behav_outcome_vapes___6", drug: "vapes", outcome: "behaviour", definition: "Knowledge, awareness or confidence"},
    {variable: "behav_outcome_vapes___7", drug: "vapes", outcome: "behaviour", definition: "Parenting"},
    {variable: "behav_outcome_vapes___8", drug: "vapes", outcome: "behaviour", definition: "Accessibility"},
    {variable: "behav_outcome_vapes___9", drug: "vapes", outcome: "behaviour", definition: "Self efficacy"},

    {variable: "behav_outcome_smokeless___1", drug: "smokeless", outcome: "behaviour", definition: "Unlawful supply / Refusal of service"},
    {variable: "behav_outcome_smokeless___2", drug: "smokeless", outcome: "behaviour", definition: "Unlawfully purchased / obtained"},
    {variable: "behav_outcome_smokeless___3", drug: "smokeless", outcome: "behaviour", definition: "Intentions and attitudes"},
    {variable: "behav_outcome_smokeless___4", drug: "smokeless", outcome: "behaviour", definition: "Desire to quit"},
    {variable: "behav_outcome_smokeless___5", drug: "smokeless", outcome: "behaviour", definition: "Peer related factors"},
    {variable: "behav_outcome_smokeless___6", drug: "smokeless", outcome: "behaviour", definition: "Knowledge, awareness or confidence"},
    {variable: "behav_outcome_smokeless___7", drug: "smokeless", outcome: "behaviour", definition: "Parenting"},
    {variable: "behav_outcome_smokeless___8", drug: "smokeless", outcome: "behaviour", definition: "Accessibility"},
    {variable: "behav_outcome_smokeless___9", drug: "smokeless", outcome: "behaviour", definition: "Self efficacy"},

    {variable: "behav_outcome_cigarette___1", drug: "cigarette", outcome: "behaviour", definition: "Unlawful supply / Refusal of service"},
    {variable: "behav_outcome_cigarette___2", drug: "cigarette", outcome: "behaviour", definition: "Unlawfully purchased / obtained"},
    {variable: "behav_outcome_cigarette___3", drug: "cigarette", outcome: "behaviour", definition: "Intentions and attitudes"},
    {variable: "behav_outcome_cigarette___4", drug: "cigarette", outcome: "behaviour", definition: "Desire to quit"},
    {variable: "behav_outcome_cigarette___5", drug: "cigarette", outcome: "behaviour", definition: "Peer related factors"},
    {variable: "behav_outcome_cigarette___6", drug: "cigarette", outcome: "behaviour", definition: "Knowledge, awareness or confidence"},
    {variable: "behav_outcome_cigarette___7", drug: "cigarette", outcome: "behaviour", definition: "Parenting"},
    {variable: "behav_outcome_cigarette___8", drug: "cigarette", outcome: "behaviour", definition: "Accessibility"},
    {variable: "behav_outcome_cigarette___9", drug: "cigarette", outcome: "behaviour", definition: "Self efficacy"},

    {variable: "behav_outcome_second___1", drug: "second", outcome: "behaviour", definition: "Unlawful supply / Refusal of service"},
    {variable: "behav_outcome_second___2", drug: "second", outcome: "behaviour", definition: "Unlawfully purchased / obtained"},
    {variable: "behav_outcome_second___3", drug: "second", outcome: "behaviour", definition: "Intentions and attitudes"},
    {variable: "behav_outcome_second___4", drug: "second", outcome: "behaviour", definition: "Desire to quit"},
    {variable: "behav_outcome_second___5", drug: "second", outcome: "behaviour", definition: "Peer related factors"},
    {variable: "behav_outcome_second___6", drug: "second", outcome: "behaviour", definition: "Knowledge, awareness or confidence"},
    {variable: "behav_outcome_second___7", drug: "second", outcome: "behaviour", definition: "Parenting"},
    {variable: "behav_outcome_second___8", drug: "second", outcome: "behaviour", definition: "Accessibility"},
    {variable: "behav_outcome_second___9", drug: "second", outcome: "behaviour", definition: "Self efficacy"},

    {variable: "behav_outcome_other___1", drug: "other", outcome: "behaviour", definition: "Unlawful supply / Refusal of service"},
    {variable: "behav_outcome_other___2", drug: "other", outcome: "behaviour", definition: "Unlawfully purchased / obtained"},
    {variable: "behav_outcome_other___3", drug: "other", outcome: "behaviour", definition: "Intentions and attitudes"},
    {variable: "behav_outcome_other___4", drug: "other", outcome: "behaviour", definition: "Desire to quit"},
    {variable: "behav_outcome_other___5", drug: "other", outcome: "behaviour", definition: "Peer related factors"},
    {variable: "behav_outcome_other___6", drug: "other", outcome: "behaviour", definition: "Knowledge, awareness or confidence"},
    {variable: "behav_outcome_other___7", drug: "other", outcome: "behaviour", definition: "Parenting"},
    {variable: "behav_outcome_other___8", drug: "other", outcome: "behaviour", definition: "Accessibility"},
    {variable: "behav_outcome_other___9", drug: "other", outcome: "behaviour", definition: "Self efficacy"}

];